version: "3"

services:
  db:
    container_name: db
    image: postgres:15
    env_file: ./.envs/.dev
    ports:
      - "5432:5432"
    networks:
      - backend_network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  ubuntu_server:
    container_name: ubuntu_server
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: ubuntu:latest
    env_file: ./.envs/.dev
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "22:22"
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  db_data:
